### ISSUE TITLE
Weapon Head Moulds Do Not Work

### ISSUE THREAD

**Issue by cyancodon** [tiigerbones/hephaestusexpansion#1]
The casts for the weapon heads for this mod do not seem to be functional making any metal that needs to the casted using the smeltery unobtainable in survival.

**Comment by tiigerbones** [comment]
ill be pushing an update to fix this issue by today! thanks for letting me know.
EDIT: This might take awhile since ive been having a lot of business trips lately.

**Comment by tiigerbones** [comment]
Fixed this issue in the latest commit!
just gotta tweak a few more things and ill be pushing the update tonight!
